### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by TorrentW** [evennode/github-actions-deploy-to-evennode#1]
Warning: Permanently added the ECDSA host key for IP address '35.204.135.88' to the list of known hosts.
Load key "/home/runner/.ssh/id_rsa": invalid format
git@git.evennode.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Process completed with exit code 128.

**Comment by ceecko** [comment]
@TorrentW the error says your private key is in invalid format.

You need to make sure to use a key in OpenSSH format. If you're using PuTTYGen, make sure to go to `Conversions > Export OpenSSH key`.

This issue is not related to this repository.

**Comment by easella** [comment]
yeah it also says theres an error
but i am on a school chromebook and linux permission is denied
is there anyway for me to create a private key?

**Comment by ceecko** [comment]
I'm not sure if Chromebooks support generating SSH keys. I recommending googling a bit.

**Comment by easella** [comment]
you can but you need to install an extension and my school blocks all chrome extensions
