### ISSUE TITLE
default branch "master" causes problem on default branches with default name "main"

### ISSUE THREAD

**Issue by this-is-michael** [evennode/github-actions-deploy-to-evennode#2]
Dear evennode team,

I have been struggling for a while to get my github integration via actions to work.
Reason was that you're using 'master' as the name of the branch, whereas most code I've worked with so far (I'm not a professional programmer) used the name 'main' for its main branch.

Independent of one's actual naming and preferences, it may help future users if you enriched the commenary both here on github and on the evennode blog to reflect that the name of the branch does matter / needs to be custom-fitted in 2 locations of the code.

Hope this is helpful.

Best, Michael

**Comment by ceecko** [comment]
Thank you for your feedback!
This has been resolved in 9eb7d0f
